### ISSUE TITLE
hi! how can i use this as a chrome extension?

### ISSUE THREAD

**Issue by willkof2** [sienatime/ocr-jpn#1]

**Comment by sienatime** [comment]
Hi! I never really deployed this project so you'd have to set it all up locally, which I also never documented, and the project is about 7 years old now, so I'm sure there would be some changes required. You should check out [Yomiwa](https://www.yomiwa.net/), I promise it will be a much better experience :) Thanks for your interest!

**Comment by willkof2** [comment]
thanks for answering me, i wanted a desktop solution but i can't find anything satisfactory so far. good luck on your projects!
